---
title: "my blog"
date: 2020-12-18
---
author: Subham Das
email: dsubham776@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello Everyone, this is my first blog which I have created through github pages. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  dsubham76 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
